 fCC = gcc -o
CFLAGS = -Wall -Wextra -Wpedantic -std=$(STD) -Wno-unused-parameter
STD= gnu11
RM = rm -f

TARGET = fork_var 

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(TARGET) $(TARGET).o

fork_var: fork_var.c
	$(CC) fork_var fork_var.c $(CFLAGS)
