all: va memory-user memory-user-v2

clean:
	rm -f va memory-user memory-user-v2

va: va.c
	gcc -o va va.c -Wall

memory-user: memory-user.c
	gcc -o memory-user memory-user.c -Wall

memory-user-v2: memory-user-v2
	gcc -o memory-user-v2 memory-user-v2.c -Wall
